/*

ComputerChoice: 
- Use Math.random function to generate random number 0.1 to 1.0
- Divide 1 into 3 parts and output different choice depeding on number
- 1/3 = Rock, 2/3 = Paper, Scissors in Else Block

HumanChoice:
- Use prompt function to take input and return the value
- Store it in a variable

Tracking Score: 
- Compare Values Generated By Computer and User
- Using If Statement Determine Winner and Increment Winners Score

*/
function getComputerChoice() {
    let RandomNumber = Math.random();
    let Choice;

    if (RandomNumber < (1 / 3))
    {
        Choice="Rock"; // 0 to ~0.33
    }
    else if (RandomNumber < (2 / 3)){
        Choice = "Paper"; // ~0.33 to ~0.67
    }
    else {
        Choice = "Scissors"; // ~0.67 to 1
    }
    Choice = Choice.toLowerCase();
    console.log("Computer Entered: ", Choice);
    return Choice;
}


function getHumanChoice() {
    let input = prompt("Enter Your Choice").toLowerCase();
    if (input == "rock" || input == "paper" || input == "scissors") {
        console.log("User Entered: ", input);
    }
    else {alert("Invalid Input");}
    return input;
}


function playRound(humanChoice, computerChoice) {
    if (humanChoice == "rock" && computerChoice == "rock" || humanChoice == "paper" && computerChoice == "paper" || humanChoice == "scissors" && computerChoice == "scissors" ) 
    {
        console.log("Try Again");
    }
    else if (humanChoice == "rock" && computerChoice == "scissors") 
    {
        console.log("You Win! Rock Beats Scissors");
    }
    else if (humanChoice == "scissors" && computerChoice == "rock")
    {
        console.log("You Lose! Rock Beats Scissors");
    }
    else if (humanChoice == "scissors" && computerChoice == "paper" )
    {
        console.log("You Win! Scissors Beats Paper");
    }
    else if (humanChoice == "paper" && computerChoice == "scissors") 
    {
        console.log("You Lose! Scissors Beats Paper");
    }
    else if (humanChoice == "paper" && computerChoice == "rock" )
    {
        console.log("You Win! Paper Beats Rock");
    }
    else if (humanChoice == "rock" && computerChoice == "paper") {
        console.log("You Lose! Paper Beats Rock");
    }
}


//Keep Track of Score

let HumanChoice = getHumanChoice();
let ComputerChoice = getComputerChoice();

playRound(HumanChoice, ComputerChoice);


let humanScore = 0, computerScore = 0;